image: maven:3.6.3-jdk-11

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - mvn test -B

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=meeting-organizer-diploma --api-key=$HEROKU_API_KEY
  only:
    - master
